/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFAZ_H_RPCGEN
#define _INTERFAZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param {
	int primero;
	int segundo;
};
typedef struct param param;

#define EJERCICIO1 0x20000199
#define EJERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(param , CLIENT *);
extern  int * suma_1_svc(param , struct svc_req *);
#define RESTA 2
extern  int * resta_1(param , CLIENT *);
extern  int * resta_1_svc(param , struct svc_req *);
#define MULTIPLICA 3
extern  int * multiplica_1(param , CLIENT *);
extern  int * multiplica_1_svc(param , struct svc_req *);
#define DIVIDE 4
extern  int * divide_1(param , CLIENT *);
extern  int * divide_1_svc(param , struct svc_req *);
extern int ejercicio1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICA 3
extern  int * multiplica_1();
extern  int * multiplica_1_svc();
#define DIVIDE 4
extern  int * divide_1();
extern  int * divide_1_svc();
extern int ejercicio1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFAZ_H_RPCGEN */
