/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interfaz.h"

int *
suma_1_svc(param arg1,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1.primero + arg1.segundo;

	return &result;
}

int *
resta_1_svc(param arg1,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1.primero - arg1.segundo;

	return &result;
}

int *
multiplica_1_svc(param arg1,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1.primero * arg1.segundo;

	return &result;
}

int *
divide_1_svc(param arg1,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1.primero / arg1.segundo;

	return &result;
}
