/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interfaz.h"


void
ejercicio2_1(char *host, args1 argum, int opc)
{	
	CLIENT *clnt;
	int  *result_1;
	resultadoAsociacion  *result_2;
	int *result_3;
	listaResultados *result_4;
	struct diccionario *daux;
	
#ifndef	DEBUG
	clnt = clnt_create (host, EJERCICIO2, EJERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	switch(opc){
		case 1:
			result_1 = ponerasociacion_1(argum, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else{
					if(*result_1 == 0)
						printf("\nSe ha introducido una nueva asociacion.\n");
					else
						printf("\nSe ha modificado el valor de una asociacion ya existente.\n");
			}

			break;

		case 2:			
			result_2 = obtenerasociacion_1(argum, clnt);
			if (result_2->estado == 0)
				printf("\nNo existe esa asociacion.\n");
			else
				printf("\nResultado de la asociacion: %s\n", result_2->resultadoAsociacion_u.val);

			xdr_free((xdrproc_t) xdr_resultadoAsociacion, (char *) result_2); //liberamos la memoria
			break;

		case 3:
			result_3 = borrarasociacion_1(argum, clnt);
			if(*result_3 == 1)
				printf("\nLa asociación ha sido eliminada.\n");
			else
				printf("\nNo existe esa asociacion.\n");

			break;

		case 4:
			result_4 = enumerar_1(argum.i, clnt);
			if(result_4->estado == 0)
				printf("\nNo existe ninguna lista de diccionarios con ese identificador.\n");
			else{
				daux = result_4->listaResultados_u.diccio;
				if(daux == NULL)
					printf("\nEsta lista se encuentra vacia.\n");
				else{
					printf("\n         Asociaciones de la lista:\n");
					while(daux != NULL){
						printf("\n           ·%s--->%s\n", daux->clave, daux->valor);
						daux = daux->sig;
					}
				}				
			}

			xdr_free((xdrproc_t) xdr_listaResultados, (char *) result_4); //liberamos la memoria

			break;

		default:
			break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *clab = malloc(sizeof(char)), *valr = malloc(sizeof(char));
	int op, numlist = 1;
	args1 aux;

	do{
		printf("\n**********Menu Practica 1**********\n");
		printf("      1.Poner asociacion.\n");
		printf("      2.Obtener asociacion.\n");
		printf("      3.Borrar asociacion.\n");
		printf("      4.Enumerar.\n");
		printf("      0.Salir.\n");
		printf("\n\t\tEscoja una opcion:");
		scanf("%d",&op);

		switch(op){
			case 1:
				printf("\n      Introduzca la maquina destino: ");
				scanf("%s", host);
				printf("\n      Introduzca el numero de lista de diccionarios: ");
				scanf("%d", &numlist);
				printf("\n      Introduzca la clave del diccionario: ");
				scanf("%s", clab);
				printf("\n      Introduzca el valor del diccionario: ");
				scanf("%s", valr);

				aux.i = numlist;
				aux.c = clab;
				aux.v = valr;

				ejercicio2_1 (host, aux, op);

				break;

			case 2:
				printf("\n      Introduzca la maquina destino: ");
				scanf("%s", host);
				printf("\n      Introduzca el numero de lista de diccionarios: ");
				scanf("%d", &numlist);
				printf("\n      Introduzca la clave del diccionario: ");
				scanf("%s", clab);

				aux.i = numlist;
				aux.c = clab;
				aux.v = "";

				ejercicio2_1 (host, aux, op);

				break;

			case 3:
				printf("\n      Introduzca la maquina destino: ");
				scanf("%s", host);
				printf("\n      Introduzca el numero de lista de diccionarios: ");
				scanf("%d", &numlist);
				printf("\n      Introduzca la clave del diccionario a borrar: ");
				scanf("%s", clab);

				aux.i = numlist;
				aux.c = clab;
				aux.v = "";

				ejercicio2_1 (host, aux, op);

				break;

			case 4:
				printf("\n      Introduzca la maquina destino: ");
				scanf("%s", host);
				printf("\n      Introduzca el numero de lista de diccionarios: ");
				scanf("%d", &numlist);

				aux.i = numlist;
				aux.c = "";
				aux.v = "";

				ejercicio2_1 (host, aux, op);

			default:
				break;
		}

	}while(op != 0);

	exit (0);
}
