/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFAZ_H_RPCGEN
#define _INTERFAZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct diccionario {
	char *clave;
	char *valor;
	struct diccionario *sig;
};
typedef struct diccionario diccionario;

struct listaDiccionarios {
	int id;
	struct diccionario *dic;
	struct listaDiccionarios *sig;
};
typedef struct listaDiccionarios listaDiccionarios;

struct resultadoAsociacion {
	int estado;
	union {
		char *val;
	} resultadoAsociacion_u;
};
typedef struct resultadoAsociacion resultadoAsociacion;

struct listaResultados {
	int estado;
	union {
		struct diccionario *diccio;
	} listaResultados_u;
};
typedef struct listaResultados listaResultados;

struct argumentos {
	int i;
	char *c;
	char *v;
};
typedef struct argumentos argumentos;

typedef argumentos args1;

#define EJERCICIO2 0x20000200
#define EJERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define PONERASOCIACION 1
extern  int * ponerasociacion_1(args1 , CLIENT *);
extern  int * ponerasociacion_1_svc(args1 , struct svc_req *);
#define OBTENERASOCIACION 2
extern  resultadoAsociacion * obtenerasociacion_1(args1 , CLIENT *);
extern  resultadoAsociacion * obtenerasociacion_1_svc(args1 , struct svc_req *);
#define BORRARASOCIACION 3
extern  int * borrarasociacion_1(args1 , CLIENT *);
extern  int * borrarasociacion_1_svc(args1 , struct svc_req *);
#define ENUMERAR 4
extern  listaResultados * enumerar_1(int , CLIENT *);
extern  listaResultados * enumerar_1_svc(int , struct svc_req *);
extern int ejercicio2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PONERASOCIACION 1
extern  int * ponerasociacion_1();
extern  int * ponerasociacion_1_svc();
#define OBTENERASOCIACION 2
extern  resultadoAsociacion * obtenerasociacion_1();
extern  resultadoAsociacion * obtenerasociacion_1_svc();
#define BORRARASOCIACION 3
extern  int * borrarasociacion_1();
extern  int * borrarasociacion_1_svc();
#define ENUMERAR 4
extern  listaResultados * enumerar_1();
extern  listaResultados * enumerar_1_svc();
extern int ejercicio2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_diccionario (XDR *, diccionario*);
extern  bool_t xdr_listaDiccionarios (XDR *, listaDiccionarios*);
extern  bool_t xdr_resultadoAsociacion (XDR *, resultadoAsociacion*);
extern  bool_t xdr_listaResultados (XDR *, listaResultados*);
extern  bool_t xdr_argumentos (XDR *, argumentos*);
extern  bool_t xdr_args1 (XDR *, args1*);

#else /* K&R C */
extern bool_t xdr_diccionario ();
extern bool_t xdr_listaDiccionarios ();
extern bool_t xdr_resultadoAsociacion ();
extern bool_t xdr_listaResultados ();
extern bool_t xdr_argumentos ();
extern bool_t xdr_args1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFAZ_H_RPCGEN */
