/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interfaz.h"

bool_t
xdr_diccionario (XDR *xdrs, diccionario *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->sig, sizeof (diccionario), (xdrproc_t) xdr_diccionario))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listaDiccionarios (XDR *xdrs, listaDiccionarios *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->dic, sizeof (diccionario), (xdrproc_t) xdr_diccionario))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->sig, sizeof (listaDiccionarios), (xdrproc_t) xdr_listaDiccionarios))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultadoAsociacion (XDR *xdrs, resultadoAsociacion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	switch (objp->estado) {
	case 1:
		 if (!xdr_string (xdrs, &objp->resultadoAsociacion_u.val, ~0))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_listaResultados (XDR *xdrs, listaResultados *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	switch (objp->estado) {
	case 1:
		 if (!xdr_pointer (xdrs, (char **)&objp->listaResultados_u.diccio, sizeof (diccionario), (xdrproc_t) xdr_diccionario))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_argumentos (XDR *xdrs, argumentos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->c, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->v, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_args1 (XDR *xdrs, args1 *objp)
{
	register int32_t *buf;

	 if (!xdr_argumentos (xdrs, objp))
		 return FALSE;
	return TRUE;
}
